### ISSUE TITLE
Missing Chinese UI translation

### ISSUE THREAD

**Issue by jcome** [turtletooth/OpenToonzPortable#1]
Hi I just downloaded the portable OpenToonz, but there is no Chinese UI translation included, would you mind to add in the coming versions.
 
Thanks for the great effort.

**Comment by turtletooth** [comment]
@jcome I don't think that OpenToonz has a Chinese translation right now. As soon as it is added, I will add it to the portable version.

**Comment by jcome** [comment]
@turtletooth Chinese UI translation is available at OpenToonz master branch for some time [https://github.com/opentoonz/opentoonz/tree/master/toonz/sources/translations/chinese](url)

it is a little bit confusing, there is some other translations available in portable version but not in OpenToonz master, such as Korean.

**Comment by jcome** [comment]
Ok, just have a test for Korean, it is Chinese UI Translations in fact. ^__^

**Comment by turtletooth** [comment]
Oop!  I'm sorry I didn't know what language that was.  I will fix the error soon.  Thanks for letting me know.

**Comment by jcome** [comment]
thanks for the fix, closed now.

**Comment by turtletooth** [comment]
Glad to help.
