### ISSUE TITLE
Missing "msvcp140.dll" & "vcruntime140.dll" DLL files

### ISSUE THREAD

**Issue by PeterLemon** [turtletooth/OpenToonzPortable#1]
Hi turtletooth,

You might remember me from the Yahoo group, I was the person who was making the English translations of the Japanese only OpenToonz docs in LaTeX
I just tried your latest portable release (OTX-3-22-19) & I love it!
BTW I have one issue I need to raise, I needed to copy "msvcp140.dll" & "vcruntime140.dll" to the portable root directory for it to run out of box on Windows10 64-bit...
I think you should def add these 2 files, as it would make it run out of the box for users.
Also I deleted "msvcp120.dll" & "msvcr120.dll" in the portable root directory, & the program still seems to run perfectly, so I think these files may be removed too.
I have uploaded the missing "msvcp140.dll" & "vcruntime140.dll" I am using here: https://filebin.net/1l7irxuz545a2qgy
I hope this helps =D

Also the next thing I want to ask is not really an issue, but I'll be cheeky & ask you anyway!
I noticed the OpenToonz people have released a very nice cloud generation software called "KumoWorks" here: https://github.com/opentoonz/kumoworks

I think it would be amazing if you can make a portable version of this very useful tool, & with your skills I reckon it would be ace, complimenting your work with portable OpenToonz =D
Anyway take care & thanks so much for providing my fave distribution of OpenToonz, good luck with everything.

**Comment by turtletooth** [comment]
I took care of the second part of the question: https://github.com/turtletooth/kumoworksportable/releases

I will fix OpenToonz Portable soon.

**Comment by PeterLemon** [comment]
Hi turtletooth,

Thanks so much for the portable KumoWorks, great job =D
