### ISSUE TITLE
please where can i download opentoonz portable for ubuntu18.04 and how d i install it

### ISSUE THREAD

**Issue by willy-oss** [turtletooth/OpenToonzPortable#2]
### System Information
* **OpenToonz Version**: 
* **Operating System**: 
* **CPU**: 
* **Memory**: 
* **Graphics Card**: 
* **Graphics Tablet**:

**Comment by turtletooth** [comment]
Sorry,  but I can only build for Windows right now. But you can try OTX:
https://github.com/manongjohn/OTX
