### ISSUE TITLE
GIF sequence frame flip:  +Initial testing of Feature Test release 07-19-16

### ISSUE THREAD

**Issue by RodneyBaker** [turtletooth/OpenToonzPortable#2]
I want to thank you for all your work enhancing OpenToonz as well as making the Portable release available.

Two things that I've been looking forward to (amongst the many features) is gif animation export and further enhancements of the Pencil Test (Camera Capture) tool both of which you update in your most recent release.  Thank you.

The gif export works great with one exception which may relate to another you've mentioned with another format.  I believe it's the third frame in the exported gif sequence that flips upside down.  The sequence then returns to normal orientation.  I'm fairly sure you know about this already.

The ability to both Import and Export gif sequences is appreciated.  I don't think I'm exaggerating when I say you may have just made OpenToonz the best software for gif animation that exists in any form.  Resolving the transparency issue (assuming FFMPEG allows for such) will certainly take this to the next level.  Now I just need to find the sweet spot for exporting gifs to specific resolutions (that's all on me of course).

Sorry to cherry pick just those two features but wanted to use that as an excuse to thank you.  :)

**Comment by RodneyBaker** [comment]
Related to this issue...

I note that in Chrome that one frame plays upside down/inverted but I also note that the exact same gif file imported into OpenToonz appears to play all frames correctly.  That seems odd but might provide a clue as to what is going on.

**Comment by turtletooth** [comment]
Thanks a ton.  I still am not sure why images are sometimes upside down.  Could you do me a favor and see if it is consistent for you?  My recent tests have actually not had upside down frames.  

Two things to test if you can:
- Make a couple small animations and see if it is always the same frame that is upside down
- As the gif is exporting, the temp files are written to the same location as the final file will be.  If you make an animation long enough for you to catch a bunch of the files and copy them somewhere else, you can check them to see if any are upside down.

Sorry to ask, but I am not (currently) experiencing the issue.

Thanks again for your feedback.

**Comment by RodneyBaker** [comment]
Speaking of consistency (or lack thereof)... Just after posting that last observation I noted that upon rendering out the same gif sequence out of OT a second time (after the (presumed) frame-error'd file was re-imported into OT) the frame wasn't flipped... all frames were correctly oriented.  Say what?  Very odd.

I'll follow your instructions and also try to reduce variation on my end as I did use some options that could be problematic (and not used on your end).  An example of that would be extending a shot from 5 frames to 50 via the render panel options.

I'll add this workflow related observation as well.
I tend to forget to click the Options and set/check Looping to 'On'.
Perhaps that could either be set to On by default or a way to remember the last setting selected be found?  Most gif animations I would render loop but not sure what other users prefer.  Not sure how that could be streamlined and I'd hate to see you get counter requests to have it default to Off.  ;)

I'll try to test for short and long sequences and everything else I can think of.
This is the least I can do for all your effort so as far as I'm concerned I'll be happy to test anything you want.  :)

**Comment by RodneyBaker** [comment]
I didn't get far into testing before I found one test case that is reproducible on my end.
It relates to adjusting the FPS out of the Render Options panel (Output Settings...)

Steps to Reproduce:
Using the same frame sequence (in my case 5 frames)
Open the Output Settings menu and under Other Settings (at the bottom) set Stretch from FPS to anything greater than what is displayed in the FPS entry (25 shows in my panel).  
Anything greater than 25 produces a flipped frame in the sequence.   This appears to be frame 3 consistently for a setting of 50 but... we can get OT to flip different frames by increasing that rate.  For instance It appears to flip every other frame (i.e. every frame gets flipped just not the original) when FPS set to 100.

I may have to provide a video capture of this to demonstrate.

As adjusting the FPS in this manner is not something the average user might do this might be something of an esoteric bug but it also might hint at something else going on in OT itself.   

I note that retiming the 5 frame sequence via xsheet (with target FPS matching at 25FPS) also produces this flipping.

Something worth checking might be to see if flipping like this occurs with other image formats.  I assume it does not occur when not using FFMPEG but haven't yet included any of that in tests.

**Comment by RodneyBaker** [comment]
It appears that any retiming of the original frames leads to an inversion of a frame.
Interestingly, this is as much feature as bug as I seem to be able to control the inversion via adjustment in the xsheet.

Example:
Any six frame sequence
Rendered out without adjustment - no flipped frames

Same six frame sequence
Reframe on 4s via xsheet - flips frames (I'll have to check but I think this inverted each frame after displaying each correctly

Same siz frame sequence w/ all frames on 1s
Adjust frame 6 to be on 2s > frame 6 gets flipped on the new (duplicate) frame 7


All of this is probably clear as mud but that's what I'm seeing.
Conclusion thus far is that *any* retiming of an original sequence yields flipped frames.

**Comment by turtletooth** [comment]
Thanks!  I have been able to duplicate it.  OpenToonz spits out normal frames upside down, and I have had to flip them.  But I think for retimed frames it just reuses the same frame and spits it out again- but I had flipped it before, so it gets unflipped.  I think this doesn't have to be a hard solution, I just need to change where I flip the frame and push it farther down the process.

**Comment by RodneyBaker** [comment]
Outstanding.  Please let me know if you need anything tested.
While I watch your github and OT's continuously I can also be reached at rodney.baker at gmail.com

**Comment by turtletooth** [comment]
While definitely a bug- I have made some cool patterns with the flipping. :)

**Comment by turtletooth** [comment]
Fixed and now Looping is the default.

**Comment by turtletooth** [comment]
New build coming tomorrow

**Comment by RodneyBaker** [comment]
Outstanding!   
(Keep that flipping thing at hand... surely 'tis a feature.)  ;)

**Comment by RodneyBaker** [comment]
As of today ffmeg features have been merged into the official OpenToonz master.  Flipped/missing frames have been addressed in all the various formats.  See issue track in OpenToonz master for additional information including some options that proved useful for navigating ffmpeg issues.  Congrats!  This issue (the first and only one currently for the portable) can be closed.  :)

**Comment by turtletooth** [comment]
@RodneyBaker new portable out today with new features.  (Camera capture works now btw) :)

**Comment by RodneyBaker** [comment]
Thanks Turtletooth.  I've installed and am already enjoying your latest
portable update!  :)
(And filed a bug report as well)

**Comment by turtletooth** [comment]
Hey Rodney- Want to try this out?
https://github.com/motionmonster/motionmonster/releases/tag/v1.1.1
Not replacing OT, but meant for users who might have different needs.

**Comment by RodneyBaker** [comment]
That's outstanding.  :)
