### ISSUE TITLE
Improvement for Menu Bar on HiDPI screen

### ISSUE THREAD

**Issue by jcome** [turtletooth/OpenToonzPortable#4]
It is not an issue for portable version, instead it is an issue of official build, but seems it is partly fixed in portable version, so I would like to ask if there any changes made in portable which can be applied to fix it in up stream. Thanks.

On Windows 10 platform, when use env variable:
QT_AUTO_SCREEN_SCALE_FACTOR = 1

We can scale the OpenToonz UI to more readable, but it there is an issue for menu bar 
<img width="985" alt="official nightly build" src="https://cloud.githubusercontent.com/assets/417336/17329489/6ff51266-58f5-11e6-90aa-79a91dfb9cd6.png">

But with the latest portable version, this issue seems almost be fixed,  except when switched to room "Palette"
<img width="1025" alt="almost all rooms have no double menu issue" src="https://cloud.githubusercontent.com/assets/417336/17329736/8499bbc6-58f6-11e6-95e5-f555f74429c7.png">
<img width="1023" alt="except the Palette room" src="https://cloud.githubusercontent.com/assets/417336/17329737/85fb9e6c-58f6-11e6-99f6-1915261c4473.png">

**Comment by turtletooth** [comment]
Sorry for the late response.  I did make a change in making the tool options bar fill the entire top of the screen.  I can look at the palette window and see what might be making it different.
