### ISSUE TITLE
I'm waiting for the continuation.

### ISSUE THREAD

**Issue by GGG090** [turtletooth/OpenToonzPortable#7]
@turtletooth Please make an issue with new themes ( https://github.com/opentoonz/opentoonz/pull/1112 )  and with a project of brushes. ( https://github.com/opentoonz/opentoonz/pull/1124 ) 
![image](https://cloud.githubusercontent.com/assets/28449170/25753103/082fe29e-31c3-11e7-99c1-9002c8163856.png)

**Comment by turtletooth** [comment]
I'm currently only building portable versions of full releases.  Also the MyPaint isn't yet buildable using Visual Studio, so I can't even build one if I wanted to.
